export const ACTION_SIGN_IN = 'SIGN_IN';
export const ACTION_SIGN_OUT = 'SIGN_OUT';
export const ACTION_CREATE_STREAM = 'CREATE_STREAM';
export const ACTION_FETCH_STREAMS = 'FETCH_STREAMS';
export const ACTION_FETCH_STREAM = 'FETCH_STREAM';
export const ACTION_DELETE_STREAM = 'DELETE_STREAM';
export const ACTION_EDIT_STREAM = 'EDIT_STREAM';